#!/usr/bin/python
from __future__ import print_function
import re,argparse,itertools

def main(args):
    filename=args.tsv
    regex=args.extended_regexp
    prog=re.compile(regex)

    with open(filename) as tsv:
        #find the appropriate columns in the header that match the regex
        header=tsv.readline().split("\t")
        selector=[prog.search(h) for h in header]
        #always print the first column
        selector[0]=True
        #print the header
        print("\t".join(itertools.compress(header,selector)))


        for line in tsv:
            #skip blank lines
            if line.strip()=="":
                continue
            #if the first column matches, print the matching columns
            tokens=line.split()
            if prog.search(tokens[0]):
                print("\t".join(itertools.compress(tokens,selector)))

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Grep through a tsv to select rows AND columns that match a regular expression")
    parser.add_argument("tsv", help="the tsv to grep through")
    parser.add_argument("--extended-regexp", "-E", help="Regular expression to use for grepping (python regex)", required=True)
    args=parser.parse_args()
    main(args)

