#!/usr/bin/python
from __future__ import print_function
import sys,getopt,re
import csv,re
import argparse

def main(args):
    filename=args.tsv
    regex=args.extended_regexp

    prog=re.compile(regex)
    with open(filename) as tsv:
        #find the appropriate columns in the header that match the regex
        line=tsv.readline()
        header=line.split("\t")
        count=0
        cols=[]
        print(header[0], end='') 
        for token in header:
            if prog.search(token):
                #add the column indices to a list for use later
                cols.append(count)
                print("\t",token, end='')
            count+=1
        print()
        #in the rest of the line, find the matching rows and 
        #print the columns that match the indices found above
        while line!="":
            line=tsv.readline()
            if line.strip()=="":
                continue
            tokens=line.split()
            if prog.search(tokens[0]):
                print(tokens[0], end='')
                for col in cols:
                    print("\t",tokens[col], end='')
                print()
        

            



if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Grep through a tsv to select rows AND columns that match a regular expression")
    parser.add_argument("tsv", help="the tsv to grep through")
    parser.add_argument("--extended-regexp", "-E", help="Regular expression to use for grepping (python regex)", required=True)
    args=parser.parse_args()
    main(args)

